//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""CubeControl"",
            ""id"": ""a5a10f2c-73d7-4eba-9c8a-c1e3186256bd"",
            ""actions"": [
                {
                    ""name"": ""StopCube"",
                    ""type"": ""Button"",
                    ""id"": ""68bc2a5d-e291-45c0-b6e8-170fcbfecc08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""01678f55-3196-4875-a3c7-52ec7caecce1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopCube"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CubeControl
        m_CubeControl = asset.FindActionMap("CubeControl", throwIfNotFound: true);
        m_CubeControl_StopCube = m_CubeControl.FindAction("StopCube", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CubeControl
    private readonly InputActionMap m_CubeControl;
    private List<ICubeControlActions> m_CubeControlActionsCallbackInterfaces = new List<ICubeControlActions>();
    private readonly InputAction m_CubeControl_StopCube;
    public struct CubeControlActions
    {
        private @InputControls m_Wrapper;
        public CubeControlActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @StopCube => m_Wrapper.m_CubeControl_StopCube;
        public InputActionMap Get() { return m_Wrapper.m_CubeControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CubeControlActions set) { return set.Get(); }
        public void AddCallbacks(ICubeControlActions instance)
        {
            if (instance == null || m_Wrapper.m_CubeControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CubeControlActionsCallbackInterfaces.Add(instance);
            @StopCube.started += instance.OnStopCube;
            @StopCube.performed += instance.OnStopCube;
            @StopCube.canceled += instance.OnStopCube;
        }

        private void UnregisterCallbacks(ICubeControlActions instance)
        {
            @StopCube.started -= instance.OnStopCube;
            @StopCube.performed -= instance.OnStopCube;
            @StopCube.canceled -= instance.OnStopCube;
        }

        public void RemoveCallbacks(ICubeControlActions instance)
        {
            if (m_Wrapper.m_CubeControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICubeControlActions instance)
        {
            foreach (var item in m_Wrapper.m_CubeControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CubeControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CubeControlActions @CubeControl => new CubeControlActions(this);
    public interface ICubeControlActions
    {
        void OnStopCube(InputAction.CallbackContext context);
    }
}
